services:
  backend:
    build: ./backend
    container_name: firesport-backend
    ports:
      - "8000:8000"
      - "5679:5679"
    volumes:
      - ./backend:/app
      - ./data:/app/data:ro
    depends_on:
      - mongo
      - mailpit
    entrypoint: ["/bin/bash", "/app/entrypoint.sh"]
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - DEBUG=true
      - IMPORT_DATA=false
      - SMTP_HOST=mailpit
      - SMTP_PORT=1025
      - SMTP_USE_TLS=false
      - SMTP_USE_SSL=false
      - SMTP_FROM_EMAIL=no-reply@firesport.local
      - FRONTEND_URL=http://localhost:3000

  mongo:
    image: mongo
    container_name: firesport-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mailpit:
    image: axllent/mailpit
    container_name: firesport-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

  frontend:
    container_name: firesport-frontend
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: ""
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo-data:
