services:
  backend:
    build: ./backend
    container_name: firesport-backend
    ports:
      - "8000:8000"
      - "5679:5679"
    volumes:
      - ./backend:/app
      - ./data:/app/data:ro
    depends_on:
      - mongo
    entrypoint: ["/bin/bash", "/app/entrypoint.sh"]
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - DEBUG=true
      - IMPORT_DATA=true

  mongo:
    image: mongo
    container_name: firesport-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    container_name: firesport-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - BROWSER=none
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    command: sh -c "npm install && npm start"
    restart: unless-stopped

volumes:
  mongo-data:
